-- MySQL Script generated by MySQL Workbench
-- 03/23/17 17:23:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_car_rental
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_car_rental
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_car_rental` DEFAULT CHARACTER SET utf8 ;
USE `db_car_rental` ;

-- -----------------------------------------------------
-- Table `db_car_rental`.`Brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_car_rental`.`Brands` (
  `brand_id` INT NOT NULL,
  `brand_name` VARCHAR(45) NOT NULL,
  `brand_class` VARCHAR(45) NOT NULL,
  `brand_number_of_seats` INT NOT NULL,
  `brand_issue_year` INT NOT NULL,
  `brand_engine` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`brand_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_car_rental`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_car_rental`.`Staff` (
  `staff_id` INT NOT NULL,
  `staff_full_name` VARCHAR(45) NOT NULL,
  `staff_post` VARCHAR(45) NOT NULL,
  `staff_department` VARCHAR(45) NOT NULL,
  `staff_salary` INT NOT NULL,
  PRIMARY KEY (`staff_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_car_rental`.`Cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_car_rental`.`Cars` (
  `car_id` INT NOT NULL,
  `car_number` VARCHAR(45) NOT NULL,
  `car_category` VARCHAR(45) NOT NULL,
  `car_brand` INT NOT NULL,
  `car_staff` INT NOT NULL,
  PRIMARY KEY (`car_id`, `car_brand`, `car_staff`),
  INDEX `fk_Cars_Brands1_idx` (`car_brand` ASC),
  INDEX `fk_Cars_Staff1_idx` (`car_staff` ASC),
  CONSTRAINT `fk_Cars_Brands1`
    FOREIGN KEY (`car_brand`)
    REFERENCES `db_car_rental`.`Brands` (`brand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cars_Staff1`
    FOREIGN KEY (`car_staff`)
    REFERENCES `db_car_rental`.`Staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_car_rental`.`Insurances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_car_rental`.`Insurances` (
  `insurance_id` INT NOT NULL,
  `insurance_code` VARCHAR(45) NOT NULL,
  `insurance_cost` INT NOT NULL,
  `insurance_car` INT NOT NULL,
  `insurance_date_begin` DATE NOT NULL,
  `insurances_date_expir` DATE NOT NULL,
  PRIMARY KEY (`insurance_id`, `insurance_car`),
  INDEX `fk_Insurances_Cars1_idx` (`insurance_car` ASC),
  CONSTRAINT `fk_Insurances_Cars1`
    FOREIGN KEY (`insurance_car`)
    REFERENCES `db_car_rental`.`Cars` (`car_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_car_rental`.`Inspections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_car_rental`.`Inspections` (
  `inspection_id` INT NOT NULL,
  `inspection_cost` INT NOT NULL,
  `inspection_car` INT NOT NULL,
  `inspection_date_begin` DATE NOT NULL,
  `inspections_date_expir` DATE NOT NULL,
  PRIMARY KEY (`inspection_id`, `inspection_car`),
  INDEX `fk_Inspections_Cars1_idx` (`inspection_car` ASC),
  CONSTRAINT `fk_Inspections_Cars1`
    FOREIGN KEY (`inspection_car`)
    REFERENCES `db_car_rental`.`Cars` (`car_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_car_rental`.`Maintenances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_car_rental`.`Maintenances` (
  `maintenance_id` INT NOT NULL,
  `maintenance_defect` VARCHAR(45) NOT NULL,
  `maintenance_cost` INT NOT NULL,
  `maintenance_car` INT NOT NULL,
  `maintenance_staff` INT NOT NULL,
  `maintenance_date_begin` DATE NOT NULL,
  `maintenance_date_expir` DATE NOT NULL,
  PRIMARY KEY (`maintenance_id`, `maintenance_car`, `maintenance_staff`),
  INDEX `fk_Maintenances_Cars1_idx` (`maintenance_car` ASC),
  INDEX `fk_Maintenances_Staff1_idx` (`maintenance_staff` ASC),
  CONSTRAINT `fk_Maintenances_Cars1`
    FOREIGN KEY (`maintenance_car`)
    REFERENCES `db_car_rental`.`Cars` (`car_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Maintenances_Staff1`
    FOREIGN KEY (`maintenance_staff`)
    REFERENCES `db_car_rental`.`Staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_car_rental`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_car_rental`.`Clients` (
  `client_id` INT NOT NULL,
  `client_full_name` VARCHAR(45) NOT NULL,
  `client_number_passport` VARCHAR(45) NOT NULL,
  `client_number_license` VARCHAR(45) NOT NULL,
  `client_location` VARCHAR(45) NOT NULL,
  `client_number_phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`client_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_car_rental`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_car_rental`.`Orders` (
  `order_id` INT NOT NULL,
  `order_client` INT NOT NULL,
  `order_car` INT NOT NULL,
  `order_date_begin` DATE NOT NULL,
  `order_date_expir` DATE NOT NULL,
  PRIMARY KEY (`order_id`, `order_client`, `order_car`),
  INDEX `fk_Orders_Clients1_idx` (`order_client` ASC),
  INDEX `fk_Orders_Cars1_idx` (`order_car` ASC),
  CONSTRAINT `fk_Orders_Clients1`
    FOREIGN KEY (`order_client`)
    REFERENCES `db_car_rental`.`Clients` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Cars1`
    FOREIGN KEY (`order_car`)
    REFERENCES `db_car_rental`.`Cars` (`car_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_car_rental`.`Tariffes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_car_rental`.`Tariffes` (
  `tariff_id` INT NOT NULL,
  `tariff_name` VARCHAR(45) NOT NULL,
  `tariff_1_to_7` INT NOT NULL,
  `tariff_8_to_14` INT NOT NULL,
  `tariff_15_to_30` INT NOT NULL,
  PRIMARY KEY (`tariff_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_car_rental`.`Discounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_car_rental`.`Discounts` (
  `discount_id` INT NOT NULL,
  `discount_name` VARCHAR(45) NOT NULL,
  `discount_value` FLOAT NOT NULL,
  PRIMARY KEY (`discount_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_car_rental`.`Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_car_rental`.`Services` (
  `service_id` INT NOT NULL,
  `service_name` VARCHAR(45) NOT NULL,
  `service_cost` INT NOT NULL,
  PRIMARY KEY (`service_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_car_rental`.`Bills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_car_rental`.`Bills` (
  `bill_id` INT NOT NULL,
  `bill_code` VARCHAR(45) NOT NULL,
  `bill_cost` INT NOT NULL,
  `bill_order` INT NOT NULL,
  `bill_tariff` INT NOT NULL,
  `bill_discount` INT NOT NULL,
  PRIMARY KEY (`bill_id`, `bill_order`, `bill_tariff`, `bill_discount`),
  INDEX `fk_Bills_Groups1_idx` (`bill_order` ASC),
  INDEX `fk_bii_Tariffes1_idx` (`bill_tariff` ASC),
  INDEX `fk_bill_Discounts1_idx` (`bill_discount` ASC),
  CONSTRAINT `fk_Bills_Groups1`
    FOREIGN KEY (`bill_order`)
    REFERENCES `db_car_rental`.`Orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bii_Tariffes1`
    FOREIGN KEY (`bill_tariff`)
    REFERENCES `db_car_rental`.`Tariffes` (`tariff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bill_Discounts1`
    FOREIGN KEY (`bill_discount`)
    REFERENCES `db_car_rental`.`Discounts` (`discount_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_car_rental`.`Services_has_Bills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_car_rental`.`Services_has_Bills` (
  `bill_service` INT NOT NULL,
  `service_bill` INT NOT NULL,
  PRIMARY KEY (`bill_service`, `service_bill`),
  INDEX `fk_Services_has_Bills_Bills1_idx` (`service_bill` ASC),
  INDEX `fk_Services_has_Bills_Services1_idx` (`bill_service` ASC),
  CONSTRAINT `fk_Services_has_Bills_Services1`
    FOREIGN KEY (`bill_service`)
    REFERENCES `db_car_rental`.`Services` (`service_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Services_has_Bills_Bills1`
    FOREIGN KEY (`service_bill`)
    REFERENCES `db_car_rental`.`Bills` (`bill_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
